---
runtime: python310
entrypoint: gunicorn -b :$PORT main:app
manual_scaling:
  instances: 1
handlers:
  - url: /static
    static_dir: static
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto